name: cinema_ticket_manager
description: "Cinema Ticket Manager App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  qr_flutter: ^4.1.0

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Image upload
  image_picker: ^1.0.7
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
